### ISSUE TITLE
[dnd 3.5] Lyric Thaumaturge (CM) , Virtuoso (CAdv), Sublime Chord (CArc) bardic music times

### ISSUE THREAD

**Issue by shadowfury** [BahamutDragon/pcgen#550]
for classes Lyric Thaumaturge (CM) , Virtuoso (CAdv), Sublime Chord (CArc) bardic music times does not stack. I see that only bard levels count.

- And i think, Virtuoso bonus to Inspire courage does not really stack it seems. 
- Sublime Chord and Bard levels does not stack for Bardic Knowledge check. 

Attached character to check this

[willy.zip](https://github.com/BahamutDragon/pcgen/files/332771/willy.zip)

**Comment by BahamutDragon** [comment]
Bardic Music times was never implemented. All issues addressed.

**Comment by shadowfury** [comment]
Thanks a lot!

**Comment by shadowfury** [comment]
It looks like there are 3 issues still:

1. Sublime chord adds bonus to Bardic music times equal to Sublime Chord level, while it should add 1/2 of it's level
2. Virtuoso does not add to Bardic music times
3. Virtuoso does not add bonus to Inspire Courage (should stack with bard levels)

Character - bard 6 / Lyric Thaumaturge 2 / Virtuoso 3 / Sublime Chord 2

Bardic music times = 10 (6 from bard, 2 from LT, 2 from Sublime Chord it seems)
should be 12 (6 from bard, 2 from LT, 3 from Virtuoso, 1 from Sublime Chord)

Inspire courage +1 (as per bard 6), should be +2 (as per bard 6 + virtuoso 3 = bard9)

[willy.zip](https://github.com/BahamutDragon/pcgen/files/333573/willy.zip)

**Comment by BahamutDragon** [comment]
Fixed missing VirtuosoLVL define, and the BardicMusicLVL with /2

**Comment by shadowfury** [comment]
After update
- Bardic music times = 13, while should be 12 (Perhaps sublime still adds as full level? Or other prestiges that progress sublime chord increase Bardic Music?)
- Inspire Courage still does not stack Bard and Virtuoso levels (+1 instead +2)

**Comment by shadowfury** [comment]
Thanks a lot! Both Bardic Music and Inspire Courage looks perfect now!

**Comment by shadowfury** [comment]
Hate to mention it, but it seems, that these Sublime Chord abilities are broken now (don't see Song of Arcane Fire anymore):

1	ABILITY:Sublime Chord Class Feature|AUTOMATIC|Sublime Chord ~ Song of Arcane Power|PRESKILL:1,TYPE.Perform=12|PREVARGTEQ:SublimeMusicLvl,2
1	ABILITY:Sublime Chord Class Feature|AUTOMATIC|Sublime Chord ~ Song of Timelessness|PRESKILL:1,TYPE.Perform=16|PREVARGTEQ:SublimeMusicLvl,6
1	ABILITY:Sublime Chord Class Feature|AUTOMATIC|Sublime Chord ~ Song of Cosmic Fire|PRESKILL:1,TYPE.Perform=20|PREVARGTEQ:SublimeMusicLvl,10

due to changes in Sublime Chord Bardic music times calculations

**Comment by BahamutDragon** [comment]
Fixed, and hopefully fully resolved.

**Comment by shadowfury** [comment]
Thanks a lot, now Bard and it's prestige classes are in pristine conditions!

**Comment by gamotria** [comment]
Dear friend! 


I've found some nice soundtracks  and wanted to  share them with you, here is  the link  <http://extra.bosmovie.com/uexfvn>

mdatz20

**Comment by gamotria** [comment]
Hey! 

I've  created a  couple of web-sites and wanted to ask you some questions abou them,  please  answer them here <http://light.mohammed-rahman.com/uexzaji>. Thank  you!


Speak to you later, mdatz20

**Comment by gamotria** [comment]
Greetings, 

I've heard about a  new fish  restaurant opening  next  saturday, are you planning to go there? Here  is some  info about that  <http://knowledge.bosmovie.com/uerptnx>


Warmly, mdatz20
