### ISSUE TITLE
Eberron - Issues with warforged race traits and other content

### ISSUE THREAD

**Issue by TheAwoo** [BahamutDragon/pcgen#960]
Issue: trying to load a saved warforged character or creating one throws an error:
`java.lang.IllegalStateException: Cannot ask for contains: pcgen.core.Ability Reference Racial Traits ~ Warforged has not been resolved`

Reproduced using the master branch, ref 
`commit 99a2d9e3647222054ec8667c44b3f17d878172fa (HEAD -> master, origin/master)`

Using PCGen v6.08.00 RC8. Loaded only the core books and eberron.

Not an expert at manipulating lst files whatsoever, but managed to get rid of the missing reference errors. Patch included below:

```diff
diff --git a/data/5e/wizards_of_the_coast/supplement/unearthed_arcana/eberron/e_abilities.lst b/data/5e/wizards_of_the_coast/supplement/unearthed_arcana/eberron/e_abilities.lst
index ffb18c80..a982073e 100755
--- a/data/5e/wizards_of_the_coast/supplement/unearthed_arcana/eberron/e_abilities.lst
+++ b/data/5e/wizards_of_the_coast/supplement/unearthed_arcana/eberron/e_abilities.lst
@@ -4,9 +4,9 @@ Shifter			CATEGORY:Race	BONUS:ABILITYPOOL|Race Base|1|TYPE=Base
 Warforged			CATEGORY:Race	BONUS:ABILITYPOOL|Race Base|1|TYPE=Base		
 
 
-Changeling Base ~ Eberron	CATEGORY:Internal	TYPE:Race Base	PRERACE:1,Changeling								ABILITY:Internal|AUTOMATIC|Racial Traits ~ Changeling	
-Shifter Base ~ Eberron		CATEGORY:Internal	TYPE:Race Base	PRERACE:1,Shifter		BONUS:ABILITYPOOL|Shifter Subrace|1		ABILITY:Internal|AUTOMATIC|Racial Traits ~ Shifter		
-Warforged Base ~ Eberron	CATEGORY:Internal	TYPE:Race Base	PRERACE:1,Warforged	BONUS:ABILITYPOOL|Warforged Subrace|1	ABILITY:Internal|AUTOMATIC|Racial Traits ~ Warforged		
+Changeling Base ~ Eberron	CATEGORY:Internal	TYPE:Race Base	PRERACE:1,Changeling								ABILITY:Internal|AUTOMATIC|Race Traits ~ Changeling	
+Shifter Base ~ Eberron		CATEGORY:Internal	TYPE:Race Base	PRERACE:1,Shifter		BONUS:ABILITYPOOL|Shifter Subrace|1		ABILITY:Internal|AUTOMATIC|Race Traits ~ Shifter		
+Warforged Base ~ Eberron	CATEGORY:Internal	TYPE:Race Base	PRERACE:1,Warforged									ABILITY:Internal|AUTOMATIC|Race Traits ~ Warforged		
 
 Race Traits ~ Changeling	CATEGORY:Internal	ABILITY:Special Ability|AUTOMATIC|TYPE=Base Changeling Race Trait
 Race Traits ~ Shifter		CATEGORY:Internal	ABILITY:Special Ability|AUTOMATIC|TYPE=Base Shifter Race Trait			BONUS:ABILITYPOOL|Shifter Subrace|1	

```

Relevant logs:
```
22:43:12.111 INFO Thread-4 SourceFileLoader:534 Loading game 5e and sources [Dungeons & Dragons 5e - Core Books, Unearthed Arcana - Eberron].
22:43:12.117 LSTERROR Thread-4 CDOMControlLoader:146 DEFAULTVARIABLEVALUE found an unsupported format: HANDED (Source: file:/C:/Users/awoo/AppData/Local/PCGen/6.08.00RC8/data/5e/wizards_of_the_coast/core/universal_rules/ur__datacontrols.lst )
22:43:12.118 LSTERROR Thread-4 CDOMControlLoader:146 Failed in parsing typeStr: DEFAULTVARIABLEVALUE HANDED|Right for pcgen.cdom.content.DefaultVarValue HANDED Right
22:43:12.118 LSTERROR Thread-4 CDOMControlLoader:146 Illegal Token 'DEFAULTVARIABLEVALUE' 'HANDED|Right' for pcgen.cdom.content.DefaultVarValue HANDED Right in file:/C:/Users/awoo/AppData/Local/PCGen/6.08.00RC8/data/5e/wizards_of_the_coast/core/universal_rules/ur__datacontrols.lst
22:43:12.171 LSTERROR Thread-4 LstUtils:147 Could not get Reference Manufacturer for Category: Shifter Trait (Source: file:/C:/Users/awoo/AppData/Local/PCGen/6.08.00RC8/data/5e/wizards_of_the_coast/supplement/unearthed_arcana/eberron/e_abilities.lst )
22:43:12.171 LSTERROR Thread-4 LstUtils:147 Failed in parsing typeStr: ABILITY Shifter Trait|AUTOMATIC|Beasthide ~ Ability Score Increase for pcgen.core.Ability Beasthide
22:43:12.171 LSTERROR Thread-4 LstUtils:147 Illegal Token 'ABILITY' 'Shifter Trait|AUTOMATIC|Beasthide ~ Ability Score Increase' for pcgen.core.Ability Beasthide in file:/C:/Users/awoo/AppData/Local/PCGen/6.08.00RC8/data/5e/wizards_of_the_coast/supplement/unearthed_arcana/eberron/e_abilities.lst
22:43:12.172 LSTERROR Thread-4 LstUtils:147 Could not get Reference Manufacturer for Category: Shifter Trait (Source: file:/C:/Users/awoo/AppData/Local/PCGen/6.08.00RC8/data/5e/wizards_of_the_coast/supplement/unearthed_arcana/eberron/e_abilities.lst )
22:43:12.172 LSTERROR Thread-4 LstUtils:147 Failed in parsing typeStr: ABILITY Shifter Trait|AUTOMATIC|Beasthide ~ Shifting Feature for pcgen.core.Ability Beasthide
22:43:12.172 LSTERROR Thread-4 LstUtils:147 Illegal Token 'ABILITY' 'Shifter Trait|AUTOMATIC|Beasthide ~ Shifting Feature' for pcgen.core.Ability Beasthide in file:/C:/Users/awoo/AppData/Local/PCGen/6.08.00RC8/data/5e/wizards_of_the_coast/supplement/unearthed_arcana/eberron/e_abilities.lst
22:43:12.173 LSTERROR Thread-4 LstUtils:147 Could not get Reference Manufacturer for Category: Shifter Trait (Source: file:/C:/Users/awoo/AppData/Local/PCGen/6.08.00RC8/data/5e/wizards_of_the_coast/supplement/unearthed_arcana/eberron/e_abilities.lst )
22:43:12.173 LSTERROR Thread-4 LstUtils:147 Failed in parsing typeStr: ABILITY Shifter Trait|AUTOMATIC|Cliffwalk ~ Ability Score Increase for pcgen.core.Ability Cliffwalk
22:43:12.174 LSTERROR Thread-4 LstUtils:147 Illegal Token 'ABILITY' 'Shifter Trait|AUTOMATIC|Cliffwalk ~ Ability Score Increase' for pcgen.core.Ability Cliffwalk in file:/C:/Users/awoo/AppData/Local/PCGen/6.08.00RC8/data/5e/wizards_of_the_coast/supplement/unearthed_arcana/eberron/e_abilities.lst
22:43:12.174 LSTERROR Thread-4 LstUtils:147 Could not get Reference Manufacturer for Category: Shifter Trait (Source: file:/C:/Users/awoo/AppData/Local/PCGen/6.08.00RC8/data/5e/wizards_of_the_coast/supplement/unearthed_arcana/eberron/e_abilities.lst )
22:43:12.174 LSTERROR Thread-4 LstUtils:147 Failed in parsing typeStr: ABILITY Shifter Trait|AUTOMATIC|Cliffwalk ~ Shifting Feature for pcgen.core.Ability Cliffwalk
22:43:12.174 LSTERROR Thread-4 LstUtils:147 Illegal Token 'ABILITY' 'Shifter Trait|AUTOMATIC|Cliffwalk ~ Shifting Feature' for pcgen.core.Ability Cliffwalk in file:/C:/Users/awoo/AppData/Local/PCGen/6.08.00RC8/data/5e/wizards_of_the_coast/supplement/unearthed_arcana/eberron/e_abilities.lst
22:43:12.175 LSTERROR Thread-4 LstUtils:147 Could not get Reference Manufacturer for Category: Shifter Trait (Source: file:/C:/Users/awoo/AppData/Local/PCGen/6.08.00RC8/data/5e/wizards_of_the_coast/supplement/unearthed_arcana/eberron/e_abilities.lst )
22:43:12.175 LSTERROR Thread-4 LstUtils:147 Failed in parsing typeStr: ABILITY Shifter Trait|AUTOMATIC|Longstride ~ Ability Score Increase for pcgen.core.Ability Longstride
22:43:12.176 LSTERROR Thread-4 LstUtils:147 Illegal Token 'ABILITY' 'Shifter Trait|AUTOMATIC|Longstride ~ Ability Score Increase' for pcgen.core.Ability Longstride in file:/C:/Users/awoo/AppData/Local/PCGen/6.08.00RC8/data/5e/wizards_of_the_coast/supplement/unearthed_arcana/eberron/e_abilities.lst
22:43:12.176 LSTERROR Thread-4 LstUtils:147 Could not get Reference Manufacturer for Category: Shifter Trait (Source: file:/C:/Users/awoo/AppData/Local/PCGen/6.08.00RC8/data/5e/wizards_of_the_coast/supplement/unearthed_arcana/eberron/e_abilities.lst )
22:43:12.176 LSTERROR Thread-4 LstUtils:147 Failed in parsing typeStr: ABILITY Shifter Trait|AUTOMATIC|Longstride ~ Shifting Feature for pcgen.core.Ability Longstride
22:43:12.177 LSTERROR Thread-4 LstUtils:147 Illegal Token 'ABILITY' 'Shifter Trait|AUTOMATIC|Longstride ~ Shifting Feature' for pcgen.core.Ability Longstride in file:/C:/Users/awoo/AppData/Local/PCGen/6.08.00RC8/data/5e/wizards_of_the_coast/supplement/unearthed_arcana/eberron/e_abilities.lst
22:43:12.177 LSTERROR Thread-4 LstUtils:147 Could not get Reference Manufacturer for Category: Shifter Trait (Source: file:/C:/Users/awoo/AppData/Local/PCGen/6.08.00RC8/data/5e/wizards_of_the_coast/supplement/unearthed_arcana/eberron/e_abilities.lst )
22:43:12.178 LSTERROR Thread-4 LstUtils:147 Failed in parsing typeStr: ABILITY Shifter Trait|AUTOMATIC|Longtooth ~ Ability Score Increase for pcgen.core.Ability Longtooth
22:43:12.178 LSTERROR Thread-4 LstUtils:147 Illegal Token 'ABILITY' 'Shifter Trait|AUTOMATIC|Longtooth ~ Ability Score Increase' for pcgen.core.Ability Longtooth in file:/C:/Users/awoo/AppData/Local/PCGen/6.08.00RC8/data/5e/wizards_of_the_coast/supplement/unearthed_arcana/eberron/e_abilities.lst
22:43:12.178 LSTERROR Thread-4 LstUtils:147 Could not get Reference Manufacturer for Category: Shifter Trait (Source: file:/C:/Users/awoo/AppData/Local/PCGen/6.08.00RC8/data/5e/wizards_of_the_coast/supplement/unearthed_arcana/eberron/e_abilities.lst )
22:43:12.179 LSTERROR Thread-4 LstUtils:147 Failed in parsing typeStr: ABILITY Shifter Trait|AUTOMATIC|Longtooth ~ Shifting Feature for pcgen.core.Ability Longtooth
22:43:12.179 LSTERROR Thread-4 LstUtils:147 Illegal Token 'ABILITY' 'Shifter Trait|AUTOMATIC|Longtooth ~ Shifting Feature' for pcgen.core.Ability Longtooth in file:/C:/Users/awoo/AppData/Local/PCGen/6.08.00RC8/data/5e/wizards_of_the_coast/supplement/unearthed_arcana/eberron/e_abilities.lst
22:43:12.180 LSTERROR Thread-4 LstUtils:147 Could not get Reference Manufacturer for Category: Shifter Trait (Source: file:/C:/Users/awoo/AppData/Local/PCGen/6.08.00RC8/data/5e/wizards_of_the_coast/supplement/unearthed_arcana/eberron/e_abilities.lst )
22:43:12.180 LSTERROR Thread-4 LstUtils:147 Failed in parsing typeStr: ABILITY Shifter Trait|AUTOMATIC|Razorclaw ~ Ability Score Increase for pcgen.core.Ability Razorclaw
22:43:12.180 LSTERROR Thread-4 LstUtils:147 Illegal Token 'ABILITY' 'Shifter Trait|AUTOMATIC|Razorclaw ~ Ability Score Increase' for pcgen.core.Ability Razorclaw in file:/C:/Users/awoo/AppData/Local/PCGen/6.08.00RC8/data/5e/wizards_of_the_coast/supplement/unearthed_arcana/eberron/e_abilities.lst
22:43:12.181 LSTERROR Thread-4 LstUtils:147 Could not get Reference Manufacturer for Category: Shifter Trait (Source: file:/C:/Users/awoo/AppData/Local/PCGen/6.08.00RC8/data/5e/wizards_of_the_coast/supplement/unearthed_arcana/eberron/e_abilities.lst )
22:43:12.181 LSTERROR Thread-4 LstUtils:147 Failed in parsing typeStr: ABILITY Shifter Trait|AUTOMATIC|Razorclaw ~ Shifting Feature for pcgen.core.Ability Razorclaw
22:43:12.181 LSTERROR Thread-4 LstUtils:147 Illegal Token 'ABILITY' 'Shifter Trait|AUTOMATIC|Razorclaw ~ Shifting Feature' for pcgen.core.Ability Razorclaw in file:/C:/Users/awoo/AppData/Local/PCGen/6.08.00RC8/data/5e/wizards_of_the_coast/supplement/unearthed_arcana/eberron/e_abilities.lst
22:43:12.182 LSTERROR Thread-4 LstUtils:147 Could not get Reference Manufacturer for Category: Shifter Trait (Source: file:/C:/Users/awoo/AppData/Local/PCGen/6.08.00RC8/data/5e/wizards_of_the_coast/supplement/unearthed_arcana/eberron/e_abilities.lst )
22:43:12.182 LSTERROR Thread-4 LstUtils:147 Failed in parsing typeStr: ABILITY Shifter Trait|AUTOMATIC|Wildhunt ~ Ability Score Increase for pcgen.core.Ability Wildhunt
22:43:12.182 LSTERROR Thread-4 LstUtils:147 Illegal Token 'ABILITY' 'Shifter Trait|AUTOMATIC|Wildhunt ~ Ability Score Increase' for pcgen.core.Ability Wildhunt in file:/C:/Users/awoo/AppData/Local/PCGen/6.08.00RC8/data/5e/wizards_of_the_coast/supplement/unearthed_arcana/eberron/e_abilities.lst
22:43:12.183 LSTERROR Thread-4 LstUtils:147 Could not get Reference Manufacturer for Category: Shifter Trait (Source: file:/C:/Users/awoo/AppData/Local/PCGen/6.08.00RC8/data/5e/wizards_of_the_coast/supplement/unearthed_arcana/eberron/e_abilities.lst )
22:43:12.183 LSTERROR Thread-4 LstUtils:147 Failed in parsing typeStr: ABILITY Shifter Trait|AUTOMATIC|Wildhunt ~ Shifting Feature for pcgen.core.Ability Wildhunt
22:43:12.183 LSTERROR Thread-4 LstUtils:147 Illegal Token 'ABILITY' 'Shifter Trait|AUTOMATIC|Wildhunt ~ Shifting Feature' for pcgen.core.Ability Wildhunt in file:/C:/Users/awoo/AppData/Local/PCGen/6.08.00RC8/data/5e/wizards_of_the_coast/supplement/unearthed_arcana/eberron/e_abilities.lst
22:43:13.461 SEVERE Thread-4 BonusLst:144 BONUS: ABILITYPOOL|WARFORGED SUBRACE|1 in Ability Warforged Base ~ Eberron contained an invalid AbilityCategory WARFORGED SUBRACE (Source: file:/C:/Users/awoo/AppData/Local/PCGen/6.08.00RC8/data/5e/wizards_of_the_coast/supplement/unearthed_arcana/eberron/e_abilities.lst )
22:43:13.761 SEVERE Thread-4 AbilityCategory:694 Unconstructed Reference: Ability Category Internal Racial Traits ~ Changeling
22:43:13.762 SEVERE Thread-4 AbilityCategory:694 Unconstructed Reference: Ability Category Internal Racial Traits ~ Shifter
22:43:13.762 SEVERE Thread-4 AbilityCategory:694 Unconstructed Reference: Ability Category Internal Racial Traits ~ Warforged
```

**Comment by BahamutDragon** [comment]
Just so I understand, you are using the MASTER branch data with 6.08 versions of PCGen? Cause that's what the major issue with the HANDED is about. (Master should be using 6.09 or later).

I have pushed the patches to both branches. Give that a go and let me know if the issue is resolved for you.

**Comment by TheAwoo** [comment]
Thank you for pointing out the issue in my report! Retested using the old ref on 6.09 - getting the exact same error when loading up my character.

The patch has fixed the problem of not being able to load up the character sheet for both versions. There's still a bit of a wrinkle however:

## 6.08
```
11:19:07.191 SEVERE Thread-8 BonusLst:144 BONUS: ABILITYPOOL|WARFORGED SUBRACE|1 in Ability Warforged Base ~ Eberron contained an invalid AbilityCategory WARFORGED SUBRACE (Source: file:/C:/Users/awoo/AppData/Local/PCGen/6.08.00RC8/data/5e/wizards_of_the_coast/supplement/unearthed_arcana/eberron/e_abilities.lst )
```

## 6.09
```
2020-02-24T10:18:01.541300300 SEVERE SwingWorker-pool-5-thread-1 BonusLst:144 BONUS: ABILITYPOOL|WARFORGED SUBRACE|1 in Ability Warforged Base ~ Eberron contained an invalid AbilityCategory WARFORGED SUBRACE (Source: file:/C:/Users/awoo/AppData/Local/PCGen/6.09.03/data/5e/wizards_of_the_coast/supplement/unearthed_arcana/eberron/e_abilities.lst )
```

Tried to solve the issue (it's not a load blocker, but still an issue) and came up with this. I'm not aware of any warforged subraces and trying to find any in the data files yielded no results, so getting rid of the reference seems like a decent enough fix.

```diff
diff --git a/data/5e/wizards_of_the_coast/supplement/unearthed_arcana/eberron/e_abilities.lst b/data/5e/wizards_of_the_coast/supplement/unearthed_arcana/eberron/e_abilities.lst
index 262edc11..01c3a181 100755
--- a/data/5e/wizards_of_the_coast/supplement/unearthed_arcana/eberron/e_abilities.lst
+++ b/data/5e/wizards_of_the_coast/supplement/unearthed_arcana/eberron/e_abilities.lst
@@ -6,7 +6,7 @@ Warforged			CATEGORY:Race	BONUS:ABILITYPOOL|Race Base|1|TYPE=Base
 
 Changeling Base ~ Eberron	CATEGORY:Internal	TYPE:Race Base	PRERACE:1,Changeling								ABILITY:Internal|AUTOMATIC|Race Traits ~ Changeling	
 Shifter Base ~ Eberron		CATEGORY:Internal	TYPE:Race Base	PRERACE:1,Shifter		BONUS:ABILITYPOOL|Shifter Subrace|1		ABILITY:Internal|AUTOMATIC|Race Traits ~ Shifter		
-Warforged Base ~ Eberron	CATEGORY:Internal	TYPE:Race Base	PRERACE:1,Warforged	BONUS:ABILITYPOOL|Warforged Subrace|1	ABILITY:Internal|AUTOMATIC|Race Traits ~ Warforged		
+Warforged Base ~ Eberron	CATEGORY:Internal	TYPE:Race Base	PRERACE:1,Warforged									ABILITY:Internal|AUTOMATIC|Race Traits ~ Warforged		
 
 Race Traits ~ Changeling	CATEGORY:Internal	ABILITY:Special Ability|AUTOMATIC|TYPE=Base Changeling Race Trait
 Race Traits ~ Shifter		CATEGORY:Internal	ABILITY:Special Ability|AUTOMATIC|TYPE=Base Shifter Race Trait			BONUS:ABILITYPOOL|Shifter Subrace|1	
```

**Comment by BahamutDragon** [comment]
Should be fixed now mate.
